# Generated by Django 3.1.4 on 2020-12-11 11:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=1)),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('additional', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Запис на прийом',
                'verbose_name_plural': 'Записи на прийом',
                'ordering': ['-is_active', 'created_date'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('email', models.EmailField(max_length=254)),
                ('first_phone', phone_field.models.PhoneField(max_length=31)),
                ('second_phone', phone_field.models.PhoneField(max_length=31)),
                ('schedule', models.TextField(verbose_name='Графік роботи')),
            ],
            options={
                'verbose_name': 'Котактні дані',
                'verbose_name_plural': 'Котактні дані',
            },
        ),
        migrations.CreateModel(
            name='MapMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'ГеоДані',
                'verbose_name_plural': 'ГеоДані',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('url', models.URLField(verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Соціальну мережу',
                'verbose_name_plural': 'Соціальні мережі',
            },
        ),
    ]
