# Generated by Django 3.1.4 on 2020-12-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=40, verbose_name='Послуга')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=1)),
                ('description', models.CharField(max_length=500, verbose_name='Опис')),
                ('price', models.CharField(max_length=30, verbose_name='Ціна')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelServices', to='services.services', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Опис послуги',
                'verbose_name_plural': 'Опис послуг',
                'ordering': ['services'],
            },
        ),
    ]
