# Generated by Django 3.1.4 on 2020-12-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to='', verbose_name='Фон на головній сторінці')),
            ],
            options={
                'verbose_name': 'Фон',
                'verbose_name_plural': 'Фон',
                'ordering': ['-is_active'],
            },
        ),
        migrations.CreateModel(
            name='LicenseField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_field', models.CharField(max_length=255, verbose_name='Ліцензія')),
            ],
            options={
                'verbose_name': 'Ліцензія',
                'verbose_name_plural': 'Ліцензія',
            },
        ),
    ]
