# Generated by Django 3.1.4 on 2020-12-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to='', verbose_name='Обрати фото')),
                ('surname', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('second_name', models.CharField(max_length=255, verbose_name='По-батькові')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
                'ordering': ['name', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.SmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Галарея',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('doctor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.doctor', verbose_name='Головний лікар')),
            ],
            options={
                'verbose_name': 'Про Клініку',
                'verbose_name_plural': 'Про Клініку',
            },
        ),
    ]
